### ISSUE TITLE
Null Safety causes a problem 

### ISSUE THREAD

**Issue by yasinarik** [fluttercandies/extended_nested_scroll_view#53]
**Hi! Thank you for making this package available.**
 I have an urgent situation and need to implement a code by using this package. However, because of the new `null safety` migration (I think), it gives an error.

Here is the error stack:

```
The relevant error-causing widget was      NestedScrollView   lib/…/multiviewer/multi-tab-view.dart:34

When the exception was thrown, this was the stack

#0      ScrollPosition.pixels    package:flutter/…/widgets/scroll_position.dart:166

#1      new _NestedScrollPosition    package:extended_nested_scroll_view/src/old_extended_nested_scroll_view.dart:1163

#2      _NestedScrollController.createScrollPosition     package:extended_nested_scroll_view/src/old_extended_nested_scroll_view.dart:1029

#3      ScrollableState._updatePosition     package:flutter/…/widgets/scrollable.dart:406

#4      ScrollableState.didChangeDependencies    package:flutter/…/widgets/scrollable.dart:432
...
════════════════════════════════════════════════════════════════════════════════
```

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_nested_scroll_view/issues/49#
