### ISSUE TITLE
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 916 pos 12: 'activity!.isScrolling': is not true.

### ISSUE THREAD

**Issue by ghost** [fluttercandies/extended_nested_scroll_view#95]
偶尔抛出以下异常 但软件正常运行

```console

======== Exception caught by gesture ===============================================================
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 916 pos 12: 'activity!.isScrolling': is not true.

When the exception was thrown, this was the stack: 
#2      ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:916:12)
#3      _NestedScrollPosition.applyFullDragUpdate (package:extended_nested_scroll_view/src/extended_nested_scroll_view.dart:1492:7)
#4      _NestedScrollCoordinator.applyUserOffset (package:extended_nested_scroll_view/src/extended_nested_scroll_view.dart:1281:31)
#5      ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:387:14)
#6      ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:647:12)
#7      DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:449:55)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#9      DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:449:7)
#10     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:298:9)
#11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440:19)
#17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#19     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#20     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#26     _invoke1 (dart:ui/hooks.dart:185:10)
#27     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#28     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onUpdate"
Recognizer: VerticalDragGestureRecognizer#4567a
  start behavior: start
====================================================================================================

```

**Comment by berkanaslan** [comment]
Same issue on 5.0.0

**Comment by zmtzawqlp** [comment]
无法重现

**Comment by demoYang** [comment]
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/7134823/219284980-75984b78-20f7-4efd-b044-77a633f2775d.png">

**Comment by lwj1994** [comment]
same on 6.2.1

**Comment by zmtzawqlp** [comment]
if you still meet this problem, please provide a simple runnable demo

**Comment by lwj1994** [comment]
Sorry, I can’t provide it, but it is still necessary to document it. If it can be reproduced, I will add more information here.

**Comment by ankeet7x** [comment]
Any update on this?

**Comment by zmtzawqlp** [comment]
> Any update on this?

can you provide an demo for this issue?
